##############################################
#    Application Server Configuration
##############################################
server.port: 8080
server.ssl.enabled: true
server.ssl.key-store: classpath:security/keystore.jks
server.ssl.key-password: secret


##############################################
#    Management over HTTP
##############################################
management.security.enabled: false
management.context-path: /management
management.port: 8090
management.ssl.enabled: false
endpoints.hypermedia.enabled: true

management.info.git.mode: full
info.app.name: Template Application


##############################################
#    Database Connection Example
##############################################
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/template
#    username: root
#    password: Hello925
#    driver-class-name: com.mysql.jdbc.Driver


##############################################
#    Service Configuration Example
##############################################
company:
  name: Microsoft
  department:
    name: Azure
    employees:
      - Benjamin Wang
      - Jarod Zhang