server:
  port: 8080


#spring:
#  datasource:
#    url: jdbc:mysql://localhost/template
#    username: root
#    password: Hello925
#    driver-class-name: com.mysql.jdbc.Driver

management.security.enabled: false
endpoints.hypermedia.enabled: true

management.info.git.mode: full
info.app.name: Template Application

company:
  name: VMware
  department:
    name: SABU
    employees:
      - Benjamin Wang
      - Jarod Zhang